export const FETCH_COMPANY_SUCCESS = 'FETCH_COMPANY_SUCCESS';
export const UPDATE_COMPANY_SUCCESS = 'UPDATE_COMPANY_SUCCESS';
export const FETCH_COMPANY_FAILURE = 'FETCH_COMPANY_FAILURE';
export const UPDATE_COMPANY_FAILURE = 'UPDATE_COMPANY_FAILURE';