export const ADD_PURCHASE = 'ADD_PURCHASE';
export const GET_PURCHASES = 'GET_PURCHASES';
export const UPDATE_PURCHASE = 'UPDATE_PURCHASE';
export const DELETE_PURCHASE = 'DELETE_PURCHASE';
export const SEARCH_PURCHASES = 'SEARCH_PURCHASES';
