export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const GET_CUSTOMERS = 'GET_CUSTOMERS';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const SEARCH_CUSTOMERS = 'SEARCH_CUSTOMERS';
export const IMPORT_CUSTOMERS = 'IMPORT_CUSTOMERS';
  