export const ADD_DELIVERYCHALLAN = 'ADD_DELIVERYCHALLAN';
export const GET_DELIVERYCHALLANS = 'GET_DELIVERYCHALLANS';
export const UPDATE_DELIVERYCHALLAN = 'UPDATE_DELIVERYCHALLAN';
export const DELETE_DELIVERYCHALLAN = 'DELETE_DELIVERYCHALLAN';
export const SEARCH_DELIVERYCHALLANS = 'SEARCH_DELIVERYCHALLANS';
export const IMPORT_DELIVERYCHALLANS = 'IMPORT_DELIVERYCHALLANS';
