export const ADD_CREDITNOTE = 'ADD_CREDITNOTE';
export const GET_CREDITNOTES = 'GET_CREDITNOTES';
export const UPDATE_CREDITNOTE = 'UPDATE_CREDITNOTE';
export const DELETE_CREDITNOTE = 'DELETE_CREDITNOTE';
export const SEARCH_CREDITNOTES = 'SEARCH_CREDITNOTES';
export const IMPORT_CREDITNOTES = 'IMPORT_CREDITNOTES';
